"""Redis-backed store for horizontally scaled deployments.

Key layout (the {quiz_id} hash tag keeps every key of a quiz in one Redis
Cluster slot, so Lua scripts and pipelines stay single-shard):

    quiz:{id}:names          HASH   user_id -> display name
    quiz:{id}:lb             ZSET   user_id -> NEGATED score (see below)
    quiz:{id}:ver            STRING monotonically increasing state version
    quiz:{id}:served         HASH   "user_id|question_id" -> first-served ts
    quiz:{id}:ans:{user_id}  HASH   question_id -> points awarded

Scores are stored negated so an ascending ZRANGE yields "highest score first,
ties by user_id ascending", which matches InMemoryStore exactly.

AI-ASSISTED (Claude Code): Lua scripts and key design generated by the AI.
Verified with the shared contract suite on fakeredis (with real Lua via lupa),
including a concurrency test that fires many duplicate submissions at once.
Not yet run against a real Redis server in this environment.
"""

from __future__ import annotations

from redis.asyncio import Redis

from .base import AnswerOutcome, LeaderboardEntry, ParticipantState, SessionStore

# KEYS: names, lb, ver, served   ARGV: user_id, name, ttl
_ADD_PARTICIPANT = """
redis.call('HSET', KEYS[1], ARGV[1], ARGV[2])
local added = redis.call('ZADD', KEYS[2], 'NX', 0, ARGV[1])
if added == 1 then redis.call('INCR', KEYS[3]) end
for i = 1, 4 do redis.call('EXPIRE', KEYS[i], ARGV[3]) end
return added
"""

# KEYS: ans_user, lb, ver   ARGV: question_id, points, user_id, ttl
_RECORD_ANSWER = """
if redis.call('HSETNX', KEYS[1], ARGV[1], ARGV[2]) == 0 then
  local s = redis.call('ZSCORE', KEYS[2], ARGV[3])
  local v = redis.call('GET', KEYS[3])
  return {0, s or '0', v or '0'}
end
redis.call('EXPIRE', KEYS[1], ARGV[4])
local s = redis.call('ZINCRBY', KEYS[2], -tonumber(ARGV[2]), ARGV[3])
local v = redis.call('INCR', KEYS[3])
return {1, s, v}
"""


def _to_score(raw: bytes | str | float | None) -> int:
    if raw is None:
        return 0
    if isinstance(raw, bytes):
        raw = raw.decode()
    return int(-float(raw)) or 0  # "or 0" normalises -0


def _s(raw: bytes | str) -> str:
    return raw.decode() if isinstance(raw, bytes) else raw


class RedisStore(SessionStore):
    def __init__(self, redis: Redis, ttl_s: int = 24 * 3600) -> None:
        self._r = redis
        self._ttl = ttl_s
        self._add_participant = redis.register_script(_ADD_PARTICIPANT)
        self._record_answer = redis.register_script(_RECORD_ANSWER)

    @staticmethod
    def _k(quiz_id: str, suffix: str) -> str:
        return f"quiz:{{{quiz_id}}}:{suffix}"

    async def add_participant(self, quiz_id: str, user_id: str, name: str) -> bool:
        keys = [self._k(quiz_id, s) for s in ("names", "lb", "ver", "served")]
        added = await self._add_participant(keys=keys, args=[user_id, name, self._ttl])
        return int(added) == 1

    async def mark_served(self, quiz_id: str, user_id: str, question_id: str, ts: float) -> float:
        key, field = self._k(quiz_id, "served"), f"{user_id}|{question_id}"
        async with self._r.pipeline(transaction=True) as p:
            p.hsetnx(key, field, repr(ts))
            p.hget(key, field)
            _, first = await p.execute()
        return float(_s(first))

    async def served_at(self, quiz_id: str, user_id: str, question_id: str) -> float | None:
        raw = await self._r.hget(self._k(quiz_id, "served"), f"{user_id}|{question_id}")
        return None if raw is None else float(_s(raw))

    async def record_answer(self, quiz_id: str, user_id: str, question_id: str, points: int) -> AnswerOutcome:
        keys = [self._k(quiz_id, f"ans:{user_id}"), self._k(quiz_id, "lb"), self._k(quiz_id, "ver")]
        accepted, score, version = await self._record_answer(
            keys=keys, args=[question_id, points, user_id, self._ttl]
        )
        return AnswerOutcome(accepted=int(accepted) == 1, score=_to_score(score), version=int(_s(version)))

    async def participant(self, quiz_id: str, user_id: str) -> ParticipantState | None:
        async with self._r.pipeline(transaction=False) as p:
            p.zscore(self._k(quiz_id, "lb"), user_id)
            p.hkeys(self._k(quiz_id, f"ans:{user_id}"))
            score, answered = await p.execute()
        if score is None:
            return None
        return ParticipantState(score=_to_score(score), answered=frozenset(_s(q) for q in answered))

    async def leaderboard(self, quiz_id: str, top_n: int) -> tuple[list[LeaderboardEntry], int, int]:
        lb = self._k(quiz_id, "lb")
        async with self._r.pipeline(transaction=True) as p:
            p.zrange(lb, 0, top_n - 1, withscores=True)
            p.zcard(lb)
            p.get(self._k(quiz_id, "ver"))
            top, total, version = await p.execute()
        if not top:
            return [], int(total), int(_s(version)) if version else 0
        user_ids = [_s(u) for u, _ in top]
        names = await self._r.hmget(self._k(quiz_id, "names"), user_ids)
        entries = [
            LeaderboardEntry(rank=i + 1, user_id=u, name=_s(n) if n else u, score=_to_score(sc))
            for i, ((_, sc), u, n) in enumerate(zip(top, user_ids, names))
        ]
        return entries, int(total), int(_s(version)) if version else 0

    async def version(self, quiz_id: str) -> int:
        raw = await self._r.get(self._k(quiz_id, "ver"))
        return int(_s(raw)) if raw else 0

    async def ranks(self, quiz_id: str, user_ids: list[str]) -> dict[str, tuple[int, int]]:
        if not user_ids:
            return {}
        lb = self._k(quiz_id, "lb")
        async with self._r.pipeline(transaction=False) as p:
            for u in user_ids:
                p.zrank(lb, u)
                p.zscore(lb, u)
            raw = await p.execute()
        out: dict[str, tuple[int, int]] = {}
        for i, u in enumerate(user_ids):
            rank, score = raw[2 * i], raw[2 * i + 1]
            if rank is not None:
                out[u] = (int(rank) + 1, _to_score(score))
        return out

    async def ping(self) -> bool:
        try:
            return bool(await self._r.ping())
        except Exception:
            return False

    async def close(self) -> None:
        await self._r.aclose()
