"""One behavioural contract, run against BOTH store implementations.

AI-ASSISTED (Claude Code): suite generated by the AI. The concurrency test is
the most important one: it proves duplicate or racing submissions can never
double-count, which is the core "accurate and consistent scoring" criterion.
"""

import asyncio

import fakeredis
import pytest

from quiz_server.store import InMemoryStore
from quiz_server.store.redis_store import RedisStore


@pytest.fixture(params=["memory", "redis"])
async def store(request):
    if request.param == "memory":
        yield InMemoryStore()
    else:
        s = RedisStore(fakeredis.FakeAsyncRedis(server=fakeredis.FakeServer()))
        yield s
        await s.close()


async def test_add_participant_is_idempotent(store):
    assert await store.add_participant("Q", "alice", "Alice") is True
    assert await store.add_participant("Q", "alice", "Alice again") is False
    top, total, _ = await store.leaderboard("Q", 10)
    assert total == 1
    assert top[0].name == "Alice again"  # latest display name wins
    assert top[0].score == 0


async def test_record_answer_adds_points_once(store):
    await store.add_participant("Q", "alice", "Alice")
    first = await store.record_answer("Q", "alice", "q1", 120)
    dup = await store.record_answer("Q", "alice", "q1", 150)
    assert first.accepted and first.score == 120
    assert not dup.accepted and dup.score == 120
    assert dup.version == first.version  # rejected write does not bump version
    state = await store.participant("Q", "alice")
    assert state.score == 120 and state.answered == frozenset({"q1"})


async def test_concurrent_duplicate_submissions_count_once(store):
    await store.add_participant("Q", "alice", "Alice")
    results = await asyncio.gather(*(store.record_answer("Q", "alice", "q1", 100) for _ in range(50)))
    assert sum(r.accepted for r in results) == 1
    assert (await store.participant("Q", "alice")).score == 100


async def test_concurrent_answers_from_many_users_are_all_counted(store):
    users = [f"u{i:03d}" for i in range(100)]
    for u in users:
        await store.add_participant("Q", u, u)
    await asyncio.gather(*(store.record_answer("Q", u, q, 10) for u in users for q in ("q1", "q2", "q3")))
    top, total, _ = await store.leaderboard("Q", 200)
    assert total == 100
    assert all(e.score == 30 for e in top)


async def test_leaderboard_order_and_tiebreak(store):
    for u in ("carol", "bob", "alice", "dave"):
        await store.add_participant("Q", u, u.title())
    await store.record_answer("Q", "bob", "q1", 150)
    await store.record_answer("Q", "carol", "q1", 100)
    await store.record_answer("Q", "alice", "q1", 100)
    top, total, _ = await store.leaderboard("Q", 3)
    assert [(e.rank, e.user_id, e.score) for e in top] == [(1, "bob", 150), (2, "alice", 100), (3, "carol", 100)]
    assert total == 4
    ranks = await store.ranks("Q", ["dave", "alice", "nobody"])
    assert ranks == {"dave": (4, 0), "alice": (2, 100)}


async def test_mark_served_keeps_first_timestamp(store):
    assert await store.served_at("Q", "alice", "q1") is None
    assert await store.mark_served("Q", "alice", "q1", 1000.5) == 1000.5
    assert await store.mark_served("Q", "alice", "q1", 2000.0) == 1000.5
    assert await store.served_at("Q", "alice", "q1") == 1000.5


async def test_version_increases_on_every_change(store):
    v0 = await store.version("Q")
    await store.add_participant("Q", "alice", "Alice")
    v1 = await store.version("Q")
    await store.record_answer("Q", "alice", "q1", 0)  # even a 0-point answer is a change
    v2 = await store.version("Q")
    assert v0 < v1 < v2


async def test_quizzes_are_isolated(store):
    await store.add_participant("A", "alice", "Alice")
    await store.record_answer("A", "alice", "q1", 100)
    assert await store.participant("B", "alice") is None
    assert (await store.leaderboard("B", 10))[1] == 0


async def test_unknown_quiz_is_empty(store):
    assert await store.leaderboard("nope", 10) == ([], 0, 0)
    assert await store.ranks("nope", ["x"]) == {}
    assert await store.version("nope") == 0
