"""FastAPI application: WebSocket endpoint, REST helpers, health and metrics.

Run:  uvicorn quiz_server.app:create_app --factory --port 8000

Every dependency (store, bus, clock) can be injected, which is how the tests
run the same app on the in-memory store, on fakeredis, and as two "nodes".

AI-ASSISTED (Claude Code): app wiring and endpoint handlers generated by the
AI. Verified by tests/test_ws.py and tests/test_multinode.py, and by running
it under uvicorn with scripts/load_test.py (up to 4,000 simulated players).
"""

from __future__ import annotations

import asyncio
import contextlib
import logging
import time
from contextlib import asynccontextmanager
from pathlib import Path
from typing import Callable

from fastapi import FastAPI, HTTPException, Query, WebSocket, WebSocketDisconnect
from fastapi.responses import FileResponse, JSONResponse, Response
from prometheus_client import CONTENT_TYPE_LATEST, generate_latest
from pydantic import BaseModel, Field, ValidationError

from .bus import LocalBus, RedisBus, UpdateBus
from .config import Settings
from .connection import Connection, TokenBucket
from .hub import Hub
from .observability import Metrics, configure_logging
from .protocol import USER_ID_RE, AnswerMsg, ClientMessage, ErrorCode, PingMsg, clean_name, error
from .quizzes import QuizRepository
from .service import QuizService
from .store import InMemoryStore, SessionStore

log = logging.getLogger("quiz.app")

CLIENT_HTML = Path(__file__).resolve().parent.parent / "client" / "index.html"

CLOSE_MESSAGE_TOO_BIG = 1009
CLOSE_BAD_REQUEST = 4400
CLOSE_QUIZ_NOT_FOUND = 4404


class CreateQuizBody(BaseModel):
    title: str | None = Field(default=None, max_length=80)


def _build_backends(settings: Settings) -> tuple[SessionStore, UpdateBus]:
    if settings.store_backend == "redis":
        from redis.asyncio import Redis

        from .store.redis_store import RedisStore

        redis = Redis.from_url(settings.redis_url, health_check_interval=10,
                               socket_keepalive=True, retry_on_timeout=True)
        return RedisStore(redis, ttl_s=settings.session_ttl_s), RedisBus(redis)
    return InMemoryStore(), LocalBus()


def create_app(settings: Settings | None = None, *, store: SessionStore | None = None,
               bus: UpdateBus | None = None, quizzes: QuizRepository | None = None,
               clock: Callable[[], float] = time.time) -> FastAPI:
    settings = settings or Settings.from_env()
    configure_logging(settings.log_level)
    if store is None or bus is None:
        default_store, default_bus = _build_backends(settings)
        store, bus = store or default_store, bus or default_bus
    quizzes = quizzes or QuizRepository()
    metrics = Metrics()
    hub = Hub(store, bus, metrics, interval_s=settings.leaderboard_interval_s, top_n=settings.leaderboard_top_n)
    service = QuizService(store, hub, metrics, clock=clock)

    @asynccontextmanager
    async def lifespan(app: FastAPI):
        await bus.start()
        await hub.start()
        log.info("started", extra={"store": type(store).__name__, "bus": type(bus).__name__})
        yield
        log.info("shutting down: closing connections with 1012 so clients reconnect elsewhere")
        await hub.stop()
        await bus.stop()
        await store.close()

    app = FastAPI(title="Real-Time Vocabulary Quiz", lifespan=lifespan)
    app.state.settings, app.state.store, app.state.hub, app.state.metrics = settings, store, hub, metrics

    # -- REST --------------------------------------------------------------
    @app.get("/", include_in_schema=False)
    async def index() -> FileResponse:
        return FileResponse(CLIENT_HTML)

    @app.get("/healthz")
    async def healthz() -> dict:
        return {"status": "ok"}

    @app.get("/readyz")
    async def readyz() -> JSONResponse:
        ok = await store.ping()
        return JSONResponse({"status": "ready" if ok else "store_unavailable"}, status_code=200 if ok else 503)

    @app.get("/metrics", include_in_schema=False)
    async def prometheus_metrics() -> Response:
        return Response(generate_latest(metrics.registry), media_type=CONTENT_TYPE_LATEST)

    @app.post("/api/quizzes", status_code=201)
    async def create_quiz(body: CreateQuizBody | None = None) -> dict:
        quiz = quizzes.create_session(body.title if body else None)
        return {"quiz_id": quiz.id, "title": quiz.title, "question_count": len(quiz.questions)}

    @app.get("/api/quizzes/{quiz_id}/leaderboard")
    async def get_leaderboard(quiz_id: str, top: int = Query(10, ge=1, le=100)) -> dict:
        if quizzes.get(quiz_id) is None:
            raise HTTPException(404, "quiz not found")
        entries, total, version = await store.leaderboard(quiz_id, top)
        return {"quiz_id": quiz_id, "version": version, "total_participants": total,
                "top": [e.__dict__ for e in entries]}

    # -- WebSocket -----------------------------------------------------------
    @app.websocket("/ws/quizzes/{quiz_id}")
    async def quiz_socket(ws: WebSocket, quiz_id: str, user_id: str = "", name: str | None = None) -> None:
        # MOCKED AUTH: user_id comes from the query string. In production the
        # client sends a JWT and user_id is taken from its verified claims.
        await ws.accept()
        if not USER_ID_RE.match(user_id):
            await ws.send_json(error(ErrorCode.BAD_REQUEST, "user_id must be 1-64 chars of [A-Za-z0-9_.-]"))
            await ws.close(code=CLOSE_BAD_REQUEST)
            return
        quiz = quizzes.get(quiz_id)
        if quiz is None:
            metrics.joins.labels("quiz_not_found").inc()
            await ws.send_json(error(ErrorCode.QUIZ_NOT_FOUND, f"Quiz '{quiz_id}' does not exist"))
            await ws.close(code=CLOSE_QUIZ_NOT_FOUND)
            return

        conn = Connection(ws, quiz_id=quiz.id, user_id=user_id, name=clean_name(name, user_id),
                          queue_size=settings.send_queue_size, metrics=metrics,
                          rate_limiter=TokenBucket(settings.rate_limit_per_s, settings.rate_limit_burst))
        writer = conn.start_writer()
        try:
            await service.join(conn, quiz)
            while True:
                raw = await ws.receive_text()
                if len(raw) > settings.max_message_bytes:
                    await ws.close(code=CLOSE_MESSAGE_TOO_BIG, reason="message too large")
                    break
                if not conn.rate_limiter.allow():
                    metrics.messages_in.labels("rate_limited").inc()
                    conn.send(error(ErrorCode.RATE_LIMITED, "Too many messages, slow down"))
                    continue
                try:
                    msg = ClientMessage.validate_json(raw)
                except ValidationError as exc:
                    metrics.messages_in.labels("invalid").inc()
                    conn.send(error(ErrorCode.BAD_REQUEST, "Invalid message",
                                    details=exc.errors(include_url=False, include_context=False)))
                    continue
                metrics.messages_in.labels(msg.type).inc()
                if isinstance(msg, PingMsg):
                    conn.send({"type": "pong", "ts": time.time()})
                elif isinstance(msg, AnswerMsg):
                    try:
                        await service.answer(conn, quiz, msg)
                    except Exception:
                        # Store hiccup: tell the client, keep the socket open.
                        # Retrying is safe: record_answer is idempotent per
                        # (user, question), so nothing is ever counted twice.
                        metrics.errors.labels("answer").inc()
                        log.exception("answer failed", extra={"quiz_id": quiz.id, "user_id": user_id})
                        conn.send(error(ErrorCode.INTERNAL, "Could not record answer, please retry",
                                        question_id=msg.question_id, request_id=msg.request_id))
        except WebSocketDisconnect:
            pass
        except Exception:
            metrics.errors.labels("connection").inc()
            log.exception("connection error", extra={"quiz_id": quiz.id, "user_id": user_id})
            with contextlib.suppress(Exception):
                await ws.close(code=1011)
        finally:
            conn.close()
            await hub.unregister(conn)
            with contextlib.suppress(Exception):
                await asyncio.wait_for(writer, timeout=1.0)
            writer.cancel()
            log.info("left", extra={"quiz_id": quiz.id, "user_id": user_id})

    return app
