"""Quiz content repository (MOCKED).

In production this would be a Quiz Content Service backed by PostgreSQL, with
quiz definitions cached in each node. Here it is an in-memory dict seeded with
a demo vocabulary quiz so the real-time component can be exercised end to end.

AI-ASSISTED (Claude Code): the vocabulary questions were generated by the AI and
checked by hand for a single unambiguous correct option.
"""

from __future__ import annotations

import secrets
from dataclasses import dataclass, field


@dataclass(frozen=True)
class Question:
    id: str
    prompt: str
    options: tuple[str, ...]
    correct_index: int
    time_limit_s: float = 20.0

    def public_view(self) -> dict:
        """What the client is allowed to see: never the correct answer."""
        return {
            "id": self.id,
            "prompt": self.prompt,
            "options": list(self.options),
            "time_limit_s": self.time_limit_s,
        }


@dataclass(frozen=True)
class Quiz:
    id: str
    title: str
    questions: tuple[Question, ...]
    _by_id: dict[str, Question] = field(default_factory=dict, compare=False, repr=False)

    def __post_init__(self) -> None:
        self._by_id.update({q.id: q for q in self.questions})

    def question(self, question_id: str) -> Question | None:
        return self._by_id.get(question_id)


_DEMO_QUESTIONS = (
    Question("q1", "What does 'ephemeral' mean?",
             ("Lasting a very short time", "Extremely large", "Full of joy", "Hard to understand"), 0),
    Question("q2", "Choose the synonym of 'benevolent'.",
             ("Hostile", "Kind", "Lazy", "Curious"), 1),
    Question("q3", "What is the opposite of 'scarce'?",
             ("Rare", "Hidden", "Plentiful", "Expensive"), 2),
    Question("q4", "'Meticulous' most nearly means:",
             ("Careless", "Very careful and precise", "Quick", "Loud"), 1),
    Question("q5", "Which word means 'to make something less severe'?",
             ("Aggravate", "Alleviate", "Accumulate", "Allocate"), 1),
)


class QuizRepository:
    def __init__(self) -> None:
        self._quizzes: dict[str, Quiz] = {}
        self.add(Quiz(id="DEMO", title="Vocabulary Warm-up", questions=_DEMO_QUESTIONS))

    def add(self, quiz: Quiz) -> None:
        self._quizzes[quiz.id] = quiz

    def get(self, quiz_id: str) -> Quiz | None:
        return self._quizzes.get(quiz_id)

    def create_session(self, title: str | None = None) -> Quiz:
        """Create a new quiz session with a unique, hard-to-guess ID."""
        quiz_id = secrets.token_urlsafe(6).replace("-", "x").replace("_", "y").upper()
        quiz = Quiz(id=quiz_id, title=title or "Vocabulary Quiz", questions=_DEMO_QUESTIONS)
        self.add(quiz)
        return quiz
