"""Load test: many simulated players across many quizzes.

    python scripts/load_test.py --url ws://localhost:8000 --quizzes 20 --players 50

Each player connects, answers every question (random choice, random think
time) and records:
  * answer RTT: send "answer" -> receive "answer_result"
  * leaderboard latency: send "answer" -> first leaderboard whose version
    includes that answer (answer_result.version <= leaderboard.version)

It also checks correctness at the end: every player's final score from the
server must equal the sum of points the server reported for their answers,
and the REST leaderboard must agree.

AI-ASSISTED (Claude Code): generated by the AI. Results quoted in the README
come from running this script on the author's laptop.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import random
import statistics
import time
import urllib.request

import websockets


async def player(url: str, quiz_id: str, user_id: str, think_ms: int, stats: dict, delay_s: float = 0) -> None:
    await asyncio.sleep(delay_s)
    async with websockets.connect(f"{url}/ws/quizzes/{quiz_id}?user_id={user_id}&name={user_id}",
                                  max_queue=None, open_timeout=30) as ws:
        sent_at: float | None = None
        awaiting_version: tuple[int, float] | None = None
        earned = 0
        final_score = None
        pending = None
        async for raw in ws:
            m = json.loads(raw)
            t = m["type"]
            if t == "question":
                # Think in a separate task so this loop keeps reading pushes.
                # (Sleeping inline here inflated leaderboard latency ~3x in the
                # first run, because pushes queued up unread during the sleep.)
                async def think_then_answer(q=m["question"]):
                    nonlocal sent_at
                    await asyncio.sleep(random.uniform(0, think_ms) / 1000)
                    sent_at = time.perf_counter()
                    choice = random.randrange(len(q["options"]))
                    await ws.send(json.dumps({"type": "answer", "question_id": q["id"], "choice": choice}))
                pending = asyncio.create_task(think_then_answer())
            elif t == "answer_result":
                stats["rtt"].append(time.perf_counter() - sent_at)
                earned += m["points_awarded"]
                final_score = m["score"]
                awaiting_version = (m["version"], sent_at)
            elif t == "leaderboard":
                stats["leaderboards"] += 1
                if awaiting_version and m["version"] >= awaiting_version[0]:
                    stats["lb_latency"].append(time.perf_counter() - awaiting_version[1])
                    awaiting_version = None
            elif t == "quiz_complete":
                break
            elif t == "error":
                stats["errors"].append(m)
        stats["mismatch"] += int(final_score != earned)
        stats["done"] += 1


def pct(values: list[float], p: float) -> float:
    if not values:
        return float("nan")
    values = sorted(values)
    return values[min(len(values) - 1, int(p / 100 * len(values)))] * 1000


async def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--url", default="ws://localhost:8000")
    ap.add_argument("--quizzes", type=int, default=10)
    ap.add_argument("--players", type=int, default=50, help="players per quiz")
    ap.add_argument("--think-ms", type=int, default=500, help="max random think time per question")
    ap.add_argument("--ramp-s", type=float, default=0.0,
                    help="spread connection opens over this many seconds (real players do not all connect "
                         "in the same millisecond; macOS's default listen backlog is only 128)")
    args = ap.parse_args()

    http = args.url.replace("ws://", "http://").replace("wss://", "https://")
    quiz_ids = []
    for _ in range(args.quizzes):
        req = urllib.request.Request(f"{http}/api/quizzes", data=b"{}", headers={"Content-Type": "application/json"})
        quiz_ids.append(json.load(urllib.request.urlopen(req))["quiz_id"])

    stats = {"rtt": [], "lb_latency": [], "leaderboards": 0, "errors": [], "mismatch": 0, "done": 0}
    started = time.perf_counter()
    total = args.quizzes * args.players
    tasks = [player(args.url, q, f"p{q}_{i}", args.think_ms, stats, delay_s=random.uniform(0, args.ramp_s))
             for q in quiz_ids for i in range(args.players)]
    results = await asyncio.gather(*tasks, return_exceptions=True)
    elapsed = time.perf_counter() - started
    failures = [r for r in results if isinstance(r, Exception)]

    # Cross-check: the REST leaderboard must list every player of each quiz.
    board_ok = all(
        json.load(urllib.request.urlopen(f"{http}/api/quizzes/{q}/leaderboard"))["total_participants"] == args.players
        for q in quiz_ids
    )

    print(f"players            {total} ({args.quizzes} quizzes x {args.players})")
    print(f"completed          {stats['done']}   connection failures: {len(failures)}")
    if failures:
        print(f"  first failure    {failures[0]!r}")
    print(f"answers            {len(stats['rtt'])} in {elapsed:.1f}s ({len(stats['rtt']) / elapsed:.0f}/s)")
    print(f"answer RTT ms      p50 {pct(stats['rtt'], 50):.1f}  p95 {pct(stats['rtt'], 95):.1f}  "
          f"p99 {pct(stats['rtt'], 99):.1f}  max {max(stats['rtt'], default=0) * 1000:.1f}")
    print(f"leaderboard ms     p50 {pct(stats['lb_latency'], 50):.1f}  p95 {pct(stats['lb_latency'], 95):.1f}  "
          f"p99 {pct(stats['lb_latency'], 99):.1f}")
    naive = len(stats["rtt"]) * args.players
    print(f"leaderboard msgs   {stats['leaderboards']} received (naive per-answer fan-out would be {naive})")
    print(f"protocol errors    {len(stats['errors'])}")
    print(f"score mismatches   {stats['mismatch']}   REST totals agree: {board_ok}")
    if stats["lb_latency"]:
        print(f"mean lb latency    {statistics.mean(stats['lb_latency']) * 1000:.1f} ms")


if __name__ == "__main__":
    asyncio.run(main())
